# Generated by Django 5.2.14 on 2026-06-08 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroma_rag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sessiondocument',
            name='document_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('headings', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_entries', to='chroma_rag.sessiondocument')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='chroma_rag.chatsession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'document'], name='chroma_rag__session_70d59e_idx')],
            },
        ),
    ]
