# Generated by Django 5.2.14 on 2026-06-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroma_rag', '0002_alter_chatsession_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentmetadata',
            name='chroma_rag__session_70d59e_idx',
        ),
        migrations.AddField(
            model_name='documentmetadata',
            name='page_count',
            field=models.IntegerField(default=0),
        ),
    ]
